[versions]
cloud-build-logic = "0.0.3"
checkstyle = "10.12.5"
stylecheck = "0.2.1"
ktlint = "0.50.0"
errorprone = "2.24.1"

cloud = "2.0.0-beta.1"
cloudMinecraft = "2.0.0-SNAPSHOT"

immutables = "2.10.0"

minecraft = "1.20.4"
fabricLoader = "0.15.5"
fabricApi = "0.93.1+1.20.4"
fabricPermissionsApi = "0.2-SNAPSHOT"

[libraries]
cloud-build-logic = { module = "org.incendo:cloud-build-logic", version.ref = "cloud-build-logic" }
stylecheck = { module = "ca.stellardrift:stylecheck", version.ref = "stylecheck" }
errorproneCore = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorprone" }

cloud-bom = { module = "org.incendo:cloud-bom", version.ref = "cloud" }
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-brigadier = { module = "org.incendo:cloud-brigadier", version.ref = "cloudMinecraft" }

immutables = { group = "org.immutables", name = "value", version.ref = "immutables" }
immutablesAnnotate = { group = "org.immutables", name = "annotate", version.ref = "immutables" }

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabricApi-bom = { module = "net.fabricmc.fabric-api:fabric-api-bom", version.ref = "fabricApi" }
fabricApi-command-api-v2 = { module = "net.fabricmc.fabric-api:fabric-command-api-v2" }
fabricApi-networking-api-v1 = { module = "net.fabricmc.fabric-api:fabric-networking-api-v1" }
fabricApi-lifecycle-events-v1 = { module = "net.fabricmc.fabric-api:fabric-lifecycle-events-v1" }
fabricPermissionsApi = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabricPermissionsApi" }

neoForge = "net.neoforged:neoforge:20.4.108-beta"

[plugins]
cloud-buildLogic-spotless = { id = "org.incendo.cloud-build-logic.spotless", version.ref = "cloud-build-logic" }
cloud-buildLogic-rootProject-publishing = { id = "org.incendo.cloud-build-logic.publishing.root-project", version.ref = "cloud-build-logic" }
cloud-buildLogic-rootProject-spotless = { id = "org.incendo.cloud-build-logic.spotless.root-project", version.ref = "cloud-build-logic" }

[bundles]
immutables = ["immutables", "immutablesAnnotate"]
