modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Incendo/cloud-neoforge/issues"
showAsResourcePack = false

[[mods]]
modId = "cloud"
version = "$version"
displayName = "Cloud Command Framework"
displayURL = "https://github.com/Incendo/cloud-neoforge"
authors = "Cloud Contributors"
description = "Cloud Command Framework on NeoForge"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.cloud]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cloud]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
